### ISSUE TITLE
Optional Arc nesting

### ISSUE THREAD

**Issue by hlb8122** [filipdulic/bus-queue#20]
I've been playing around with the library and it's really nice. 

The motivation for this issue is that primary structs that I'm passing through the bus are Bytes (https://docs.rs/bytes/0.4.12/bytes/struct.Bytes.html) and tuples of Enums and bytes. Bytes already have the main body of memory enclosed in an Arc. 

This is a little uncomfortable because I essentially have a Arc<Arc<..>> for no real reason now.

I tried to switch out Send for Clone but came across the fact that the buffer is updated by use of ArcSwap. Replacing ArcSwap for a RwLock hurts performance a bit (predictably).

The other alternative here for me would be to swap the Arc for ArcSwap in the bytes library, but this is a bit of a momentous task.

Is there any advice for some sort of work around here? Thanks

**Comment by filipdulic** [comment]
Thanks for the issue, could you provide some more info on how you use the library.  bare/async or sync? 
perhaps a short snippet when you call send or broadcast.

**Comment by vladan** [comment]
~Hi @hlb8122, could you also provide a code sample of how you currently use the library?~

Thanks for trying it out! :)

**Comment by hlb8122** [comment]
https://github.com/hlb8122/rust-bitcoin-zmq/blob/master/src/lib.rs
I'm basically pipelining ZMQ subscription into a bus_queue.

https://github.com/hlb8122/rust-bitcoin-zmq/blob/7f9bc924ab3fb9295b1fae602c23f10a80ca9bd2/src/lib.rs#L76

The aim is to be able to do lots of byte manipulation later to filter/manipulate streams with slicing later on so Bytes is a good fit here.

**Comment by hlb8122** [comment]
Also, perhaps not worth opening a brand new issue..but it'd be nice to have ability to access the sub_counter (https://github.com/filipdulic/bus-queue/blob/0f31f26e976f93210f8523be018b0b00d63b9092/src/lib.rs#L196) from the sync and async subscriber in a similar way to how Arc has count methods to count number of references.

**Comment by filipdulic** [comment]
Hi, from the code you provided, you are using the Publisher Subscriber pair on a tuple of (Topic, Bytes), from my understanding you are passing these tuples as single instances, so bus_queue Publisher takes ownership of the tuple instance, wraps it in an Arc, and passes clones of the Arc to all the Subscribers. 

In this example I don't see how bus_queue could infer that an Arc is being used within one of the members of the tuple. 

Your issue in general still stands, as passing a Publisher<T> an Arc<T> should be supported with zero copy, which it is currently not. I will look into this over the next week or so. 

Regarding the sub_counter, you can expect a get method for this in the next release tomorrow.

**Comment by hlb8122** [comment]
> In this example I don't see how bus_queue could infer that an Arc is being used within one of the members of the tuple.

Yeah, I imagine there is no way. The problem is that Topic is small so I don't mind cloning it and Bytes is basically an Arc itself so I don't mind cloning that too, so I really don't need it wrapped in an arc. 

I believe that in the Bytes crate, if the slice that the Arc typically stores is sufficiently small they omit the Arc<> and just clone the slice (because it'd be cheaper). I wonder if something like this could be done here?

https://docs.rs/bytes/0.4.12/bytes/struct.Bytes.html#inline-bytes

> Regarding the sub_counter, you can expect a get method for this in the next release tomorrow.

Thanks!

**Comment by hlb8122** [comment]
> I wonder if something like this could be done here?

Going into a little more detail: If instead of `Arc<T>` being spit out by the stream, you could have a different struct wrapping the `T`. e.g. `Parcel<T>` and maybe `Parcel<T>` ~ `Arc<T>` or `T` depending on how large `T` is? Thinking out loud.

**Comment by filipdulic** [comment]
Hi, I've publisher v0.4.1 which includes a get_sub_count method on Publishers. I am still looking into Arcs...

**Comment by filipdulic** [comment]
> Going into a little more detail: If instead of Arc<T> being spit out by the stream, you could have a different struct wrapping the T. e.g. Parcel<T> and maybe Parcel<T> ~ Arc<T> or T depending on how large T is? Thinking out loud.

The idea was to avoid unnecessary copies of the objects being passed by the pub sub queue, to maximize RAM efficiency for same messages send to multiple users, this is why passing of references on the output was used, another reason is that the underlying mechanization would not work without Arc. 

Basically if you define the Publisher/Subscriber as <T> output will be Arc<T> even if you pass is an Arc<T> object.  Currently the broadcast method accepts object: T, if you pass it an ARC, it will copy the value over into the argument and create a separate Arc that will be used by the Queue. 
I am looking into ways of detecting the Arc, and passing it along.

**Comment by hlb8122** [comment]
> The idea was to avoid unnecessary copies of the objects being passed by the pub sub queue, to maximize RAM efficiency for same messages send to multiple users

What I'm trying to get at is that: if you're sending a single u8 for example then cloning the Arc (copying the pointer and incrementing the atomic counter) is going to be heavier than just copying the raw byte?
