### ISSUE TITLE
Remove default SwapSlot export Slot<T> and it's tests.

### ISSUE THREAD

**Issue by filipdulic** [filipdulic/bus-queue#54]
Since all the SwapSlot implementations in flavers are covered by tests, remove the Slot<T> export and it's test in swap_slot.rs.

**Comment by stevanmilic** [comment]
I'm clear which test we need to remove, but about what `Slot` export are you talking about?

**Comment by filipdulic** [comment]
in this [line](https://github.com/filipdulic/bus-queue/blob/f7347879da822a5a67acd62fcb85b445bcae7149/src/lib.rs#L97) in lib.rs Slot type is being publicly exported. This is what the test expects and it can be removed once the test it self is removed.

**Comment by stevanmilic** [comment]
oh I see, thanks.
